### ISSUE TITLE
Using this library on an Azure App Service

### ISSUE THREAD

**Issue by ThomasMaes** [microsoft/PhoneticMatching#21]
Hi,

We are trying to use this library in our Microsoft Bot Framework bot.
When testing it locally in our emulator we have no issues and everything works fine.
The problems start when trying to deploy this solution to our azure environment.
At that point we get the following error:

Exception message: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B).

This leads me to believe that we are missing some sort of configuration on our App Service.
Does anyone have an idea how to solve this issue?

We have tried putting our build completly in x86 and x64. We have changed the settings on the app service itself to every possible platform.

Any help would be highly appreciated.

**Comment by Mmdixon** [comment]
If it works locally, sounds like a configuration issue with Azure.
The error is related to C# trying to run code that was compiled differently than whatever is running. The PhoneticMatching nuget is a .Net Core, with a x64 native dependency.

So that means your stack has to be .Net Core (not .Net) and the platform 64bit (not Any or 32bit).

I'm not too familiar with that kind of App Service deployment configuration, but let me know if this helps.

**Comment by PieterHeemeryck** [comment]
Thank you for your comment @Mmdixon . I'm also looking at getting this issue fixed. I have been able to get it running on an Azure Function running NodeJs v10.15.2. At first, I ran into a very similar issue where it specified that it isn't a win32 application. I did have to:

- Set the 64 bit architecture in Configure -> General settings
- Change the app setting: WEBSITE_NODE_DEFAULT_VERSION = D:\Program Files\nodejs\10.15.2 as mentioned [here](https://github.com/Azure/azure-functions-nodejs-worker/issues/158#issuecomment-523580137)
- Locally use the same Node Version number (being 64 for v10.15.2), otherwise an error occurred specifying that the compiled version (which was v8.x at first) did not match the v10.x version used for hosting

So it seems if we want the C# app service to work, we need to be able somehow to run a 64 bit application. The runtime for .NET Core 64 bit seems present on an Azure app service nowadays (this was not the case in the past), but it does not seem to use it. I tried several things, such as putting everything to 64 bit (in VS csproj file, in Azure DevOps the dotnet CLI during build step, dotnet publish -r win-x64). Nothing worked, the app often won't even start because of these changes.

In a last attempt, I tried adding the self contained flag as explained [here](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-3.1&tabs=netcore-cli#deploy-the-app-framework-dependent):
`dotnet publish -r win-x64 --self-contained`

That also did not work. Is there anything else I can do to let the Azure App Service refer to the 64 bit runtime of .NET Core v2.2 ? (e.g. setting an app setting / setting PATH variable somehow...)

**Comment by ThomasMaes** [comment]
Allright, figured this out. Apparently the main issue was conflicting version.
After forcing only x64 build to the app service, the app service wouldn't start anymore.
After investigating that issue, we found out that the problem was that we were building .net Core 2.2 seems to be not installed on an azure app service. We upgraded our project to .net Core 3.0 and everyhting started working.

**Comment by Mmdixon** [comment]
I looked at the default template for Web App Bot for C#, the EchoBot, added the PhoneticMatching dependency, created an instance of a matcher and deployed it. Out of the box I see an error similar to what you are describing. There are a few things wrong with the default settings.

App Service Settings > Configuration > General settings
```
Stack: .NET Core
Platform: 64bit
```
However, this only changes IIS to 64bit, the worker still launches 32bit `dotnet`. Mainly because `web.config` has `processPath="dotnet"` but the environment PATH has something like:
```
...
D:\Program Files (x86)\dotnet
D:\Program Files\dotnet
```
So the 32bit version is always going to get picked up first.

Seeing how `web.config` gets generated on publish, overwriting the deployed version to point to the 64bit `dotnet` fixed the issue as a proof of concept.
Another way I got it to work was edit the `deploy.cmd` to `publish` with the `--runtime win-x64 --self-contained`. As this will run the 64bit `EchoBot.exe`.
I heard better luck with Linux containers too (as the env seems not as mixed up with 32 and 64 bit?).

@ThomasMaes you seemed to solve it your own way but running `dotnet --info` or `"D:\Program Files\dotnet\dotnet" --info` both had .NET Core 2.2 SDK and runtime on a fresh instance.

@PieterHeemeryck you may need to think of it as Azure DevOps needs to cross-compile for the App Service environment so watch any assumptions the host is making. Or have the App Service do the build itself (host is the same for build and runtime). Maybe this post will help you debug.
